Docker services
rodbecc/graphql-microservices pull request #11
Opened 2019-09-06 01:54 UTC by vvasc

2019-09-06 03:26 UTC, rodbecc commented on .docker/postgres/docker-compose.yml
> +        environment:
fdsf

2019-09-08 05:48 UTC, rodbecc requested changes
Seems like you are not using `docker-compose.yml`, `.env.template`, `.gitignore`, and `start_postgres.sh` files that are located under `postgres` folder. It should be ok to delete them.

2020-01-21 05:01 UTC, rodbecc approved these changes

2020-01-21 05:03 UTC, merged

2020-01-21 12:02 UTC, vvasc commented
I'll close the referred issues https://github.com/rodbecc/graphql-microservices/issues/1